program chk_values_gsw

!THIS PROGRAM PROVIDES AN EASY WAY FOR THE USER TO COMPARE RESULTS FROM 
!THE SEAWATER ROUTINES RUN LOCALLY WITH THE CHECK VALUES PROVIDED IN 
!THE VARIOUS ROUTINES

!THIS PROGRAM REQUIRES
!     CONSTANTS_0,   FILE CONSTANTS_0.F90
!     CONVERT_0,     FILE CONVERT_0.F90
!     MATHS_0,       FILE MATHS_0.F90
!     SAL_1,         FILE SAL_1.F90
!     SAL_2,         FILE SAL_2.F90
!     LIQ_F03_5,     FILE LIQ_F03_5
!     GSW_LIBRARY_5, FILE GSW_LIBRARY_5

use values_gsw

implicit none 
!character*11, private :: version = '31 Jan 2012'

call gsw_chk_values

end program
